### ISSUE TITLE
Training the Autoencoder

### ISSUE THREAD

**Issue by winards** [tntrung/gan#7]
Hello!  I have a question about this [piece of code](https://github.com/tntrung/gan/blob/master/distgan_image/distgan.py#L281-L286). Why are you training the whole autoencoder only on the MNIST dataset?

**Comment by tntrung** [comment]
Hi, thanks. Training whole auto-encoder should work for all datasets. But in the code training I just optionally train a part of autoencoder for natural image datasets since empirically, it slightly improved the quality of generated images.
